# Site settings
title: Development Blog
email: arjen@alnitak.nl
description: > # this means to ignore newlines until "baseurl:"
  My blog about writing this blog, the challanges I faced while creating the blog this way
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alnitak81
github_username:  Arjen-Smit

# Build settings
markdown: kramdown
